{
    "name": "CI",
    "on": {
        "push": null,
        "pull_request": null,
    },
    "jobs": {
        "el7-ipa": {
            "container": "centos:7",
            "steps": [
                { "run": "echo cat > dog
                          cat dog" },
                { "run": |
                      echo can > cant
                      cat cant
                },
            ],
        },
    },
}
