{
    "name": "Release",
    "on": { "push": { "tags": "v*" }},
    "jobs": {
        "release-linux": {
            "runs-on": "ubuntu-latest",
            "steps": [
                {
                    "name": "Check out code",
                    "uses": "actions/checkout@v2",
                },
                {
                    "name": "Make a fake release",
                    "run": "mkdir tag_build && echo foo > tag_build/hotdiggitydang.tar.gz && sha512sum tag_build/* > tag_build/hotdiggitydang.tar.gz.sha512sum",
                },
                {
                    "name": "Create release",
                    "uses": "actions/create-release@v1",
                    "id": "cr",
                    "env": { "GITHUB_TOKEN": "${{ secrets.GITHUB_TOKEN }}" },
                    "with": {
                        "tag_name": "${{ github.ref }}",
                        "release_name": "${{ github.ref }}",
                    },
                },
                {
                    "name": "Ugh",
                    "id": "ugh",
                    "run": "echo \"::set-output name=basename::`ls tag_build/*.tar.gz | awk -F/ '{print $2}'`\""
                },
                {
                    "name": "Upload release tarball",
                    "uses": "actions/upload-release-asset@v1",
                    "env": { "GITHUB_TOKEN": "${{ secrets.GITHUB_TOKEN }}" },
                    "with": {
                        "upload_url": "${{ steps.cr.outputs.upload_url }}",
                        "asset_path": "tag_build/${{ steps.ugh.outputs.basename }}",
                        "asset_name": "${{ steps.ugh.outputs.basename }}",
                        "asset_content_type": "application/octet-stream",
                    },
                },
                {
                    "name": "Upload release checksum",
                    "uses": "actions/upload-release-asset@v1",
                    "env": { "GITHUB_TOKEN": "${{ secrets.GITHUB_TOKEN }}" },
                    "with": {
                        "upload_url": "${{ steps.cr.outputs.upload_url }}",
                        "asset_path": "tag_build/${{ steps.ugh.outputs.basename }}.sha512sum",
                        "asset_name": "${{ steps.ugh.outputs.basename }}.sha512sum",
                        "asset_content_type": "text/plain",
                    },
                },
            ],
        },
    },
}
